[package]
name = "encoding_rs"
description = "A Gecko-oriented implementation of the Encoding Standard"
version = "0.8.22" # Remember to keep html_root_url in lib.rs in sync!
authors = ["Henri Sivonen <hsivonen@hsivonen.fi>"]
license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/encoding_rs/"
homepage = "https://docs.rs/encoding_rs/"
repository = "https://github.com/hsivonen/encoding_rs"
keywords = ["encoding", "web", "unicode", "charset"]
categories = ["text-processing", "encoding", "web-programming", "internationalization"]
exclude = ["/sgx/*"]

[badges]
travis-ci = { repository = "hsivonen/encoding_rs" }

[features]
default = ["mesalock_sgx"]

simd-accel = ["packed_simd", "packed_simd/into_bits"]
less-slow-kanji-encode = []
less-slow-big5-hanzi-encode = []
less-slow-gb-hanzi-encode = []
fast-hangul-encode = []
fast-hanja-encode = []
fast-kanji-encode = []
fast-gb-hanzi-encode = []
fast-big5-hanzi-encode = []
fast-legacy-encode = ["fast-hangul-encode",
                      "fast-hanja-encode",
                      "fast-kanji-encode",
                      "fast-gb-hanzi-encode",
                      "fast-big5-hanzi-encode"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
cfg-if = "0.1.0"
packed_simd = { version = "0.3.3", optional = true }
serde = { git = "https://github.com/mesalock-linux/serde-sgx", optional = true }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev-dependencies]
#serde_derive = "1.0"
#bincode = "1.0"
#serde_json = "1.0"

[profile.release]
lto = true
